/* Criando tabela DespesasUltimoTrimestre2022 */

CREATE TABLE DespesasUltimoTrimestre2022(
    DATA DATE,
    REG_ANS VARCHAR(10),
    CD_CONTA_CONTABIL VARCHAR(30),
    DESCRICAO VARCHAR(200),
    VL_SALDO_INICIAL DECIMAL(16,2),
    VL_SALDO_FINAL DECIMAL(16,2)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE DespesasUltimoTrimestre2022
ADD FOREIGN KEY (REG_ANS) REFERENCES Operadoras(REGISTRO_ANS);
