/* Criando tabela DespesasUltimoAno2021 */

CREATE TABLE DespesasUltimoAno2021(
    DATA DATE,
    REG_ANS VARCHAR(10),
    CD_CONTA_CONTABIL VARCHAR(30),
    DESCRICAO VARCHAR(200),
    VL_SALDO_FINAL DECIMAL(16,2)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE DespesasUltimoAno2021
ADD FOREIGN KEY (REG_ANS) REFERENCES Operadoras(REGISTRO_ANS);
